## Research questions
optie 1: To what extend is the way food is produced within Sub-Saharan africa related to hunger in sub-saharan africa and how will this trend develop until 2030? 

subquestions:
- What indicators strongly relate to zero hunger?
- How did those indicators developed in the last decades (for individual countries in subharan africa)?

- What the differences in hunger between countries? 
- What is causing these differences, is this related to the way food is produced?

- How will the indicators regarding zero hunger goals develop until 2030 under the influence of certain policies?

optie 2: What indicators strongly relate to the production of food in sub-sahara africa and and how will the overall trend in hunger in SS africa look like?

## Opbouw report
Hoofdstuk 1: introductie probleem
- Inleiding no hunger goal 2030 van UN 
- Introductie onderzoeksvragen
- Uitleggen methodologie

Hoofdstuk 2: Data preperation
- Wat voor data is gebruikt?
- Hoe is die gecleaned/bewerkt om te gebruiken

Hoofdstuk 3: uitwerken onderzoeksvragen

- Uitwerken onderzoeksvraag aan de hand van analyseren data & graphs
- Schatten van toekomst met regressie analyse / trend analyses. Aan de hand van deze gegevens een schatting maken voor al deze veriabelen, maar vooral het effect op de ondervoeding/voedseltekort

Hoofdstuk 4: aanbevelingen/conclusie


## PythonProjectQuarter1

*Assignment*
Create a Jupyter Notebook that contains your explanations and analyses. Start the notebook with a
clear description of your research question and the type of analysis you are going to perform. The
conceptual contents of the Notebook should be roughly similar to a normal written report of 10-20
pages. Make your Notebook self-explanatory. So, it should contain text (with references) as well as
your actual analysis code and results. If you want to use other libraries for your analyses or
visualizations, feel free to do so. However, only use free available and well-known libraries. The ones
that come standard with Anaconda are fine. If you want to use something else, that you first need to
install, check with us first. Create a zip archive and upload it on Brightspace.
Some (minimum) properties of the Notebook and your analyses on which we will grade:
- Demonstrate your skills in Python by using typical Python constructs and using the appropriate
data structures (lists, dictionaries, tuples, arrays, dataframes, series, recursion, etc.)
- Try to think of reusability of your code. How easy would it be to use your same code if we
want to try to do a small variations of your analysis? Can we easily adapt/play around with
your code?
- How difficult were your analyses?

## Loading in data

In [4]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

plt.style.use('ggplot')

In [47]:
df_sdg = pd.read_csv("Data//SDG//SDGData.csv")
df_wdi = pd.read_csv("Data//WDI//WDI.csv")
df_wdi
all_indicators = df_sdg["Indicator Name"].unique()
all_codes = df_sdg["Indicator Code"].unique()
type(all_codes)

numpy.ndarray

In [43]:
indicators_name_code = pd.DataFrame({'Indicator Name':list(all_indicators),'Indicator Code': list(all_codes)}, columns =['Indicator Name', 'Indicator Name'])
indicators_name_code

,Indicator Name,Indicator Name
0,Access to clean fuels and technologies for coo...,Access to clean fuels and technologies for coo...
1,Access to electricity (% of population),Access to electricity (% of population)
2,"Access to electricity, rural (% of rural popul...","Access to electricity, rural (% of rural popul..."
3,"Access to electricity, urban (% of urban popul...","Access to electricity, urban (% of urban popul..."
4,Account ownership at a financial institution o...,Account ownership at a financial institution o...
5,Account ownership at a financial institution o...,Account ownership at a financial institution o...
6,Account ownership at a financial institution o...,Account ownership at a financial institution o...
7,Account ownership at a financial institution o...,Account ownership at a financial institution o...
8,Account ownership at a financial institution o...,Account ownership at a financial institution o...
9,Account ownership at a financial institution o...,Account ownership at a financial institution o...
10,Account ownership at a financial institution o...,Account ownership at a financial institution o...
11,Account ownership at a financial institution o...,Account ownership at a financial institution o...
12,Account ownership at a financial institution o...,Account ownership at a financial institution o...
13,"Adjusted net savings, excluding particulate em...","Adjusted net savings, excluding particulate em..."
14,"Adolescent fertility rate (births per 1,000 wo...","Adolescent fertility rate (births per 1,000 wo..."
15,Adolescents out of school (% of lower secondar...,Adolescents out of school (% of lower secondar...
16,"Adolescents out of school, female (% of female...","Adolescents out of school, female (% of female..."
17,"Adolescents out of school, male (% of male low...","Adolescents out of school, male (% of male low..."
18,"Air transport, freight (million ton-km)","Air transport, freight (million ton-km)"
19,"Air transport, passengers carried","Air transport, passengers carried"
20,"Annual freshwater withdrawals, agriculture (% ...","Annual freshwater withdrawals, agriculture (% ..."
21,"Annual freshwater withdrawals, domestic (% of ...","Annual freshwater withdrawals, domestic (% of ..."
22,"Annual freshwater withdrawals, industry (% of ...","Annual freshwater withdrawals, industry (% of ..."
23,"Annual freshwater withdrawals, total (% of int...","Annual freshwater withdrawals, total (% of int..."
24,"Annual freshwater withdrawals, total (billion ...","Annual freshwater withdrawals, total (billion ..."
25,Annualized average growth rate in per capita r...,Annualized average growth rate in per capita r...
26,Annualized average growth rate in per capita r...,Annualized average growth rate in per capita r...
27,Aquaculture production (metric tons),Aquaculture production (metric tons)
28,Average transaction cost of sending remittance...,Average transaction cost of sending remittance...
29,Average transaction cost of sending remittance...,Average transaction cost of sending remittance...
...,...,...
333,"Trained teachers in primary education, male (%...","Trained teachers in primary education, male (%..."
334,Trained teachers in secondary education (% of ...,Trained teachers in secondary education (% of ...
335,"Trained teachers in secondary education, femal...","Trained teachers in secondary education, femal..."
336,"Trained teachers in secondary education, male ...","Trained teachers in secondary education, male ..."
337,Trained teachers in upper secondary education ...,Trained teachers in upper secondary education ...
338,"Trained teachers in upper secondary education,...","Trained teachers in upper secondary education,..."
339,"Trained teachers in upper secondary education,...","Trained teachers in upper secondary education,..."
340,"Unemployment, female (% of female labor force)...","Unemployment, female (% of female labor force)..."
341,"Unemployment, female (% of female labor force)...","Unemployment, female (% of female labor force)..."
342,"Unemployment, male (% of male labor force) (mo...","Unemployment, male (% of male labor force) (mo..."
343,"Unemployment, male (% of male labor force) (na...","Unemployment, male (% of male labor force) (na..."
344,"Unemployment, total (% of total labor force) (...","Unemployment, total (% of total labor force) (..."
345,"Unemployment, total (% of total labor force) (...","Unemployment, total (% of total labor force) (..."
346,"Unemployment, youth female (% of female labor ...","Unemployment, youth female (% of female labor ..."
347,"Unemployment, youth female (% of female labor ...","Unemployment, youth female (% of female labor ..."
348,"Unemployment, youth male (% of male labor forc...","Unemployment, youth male (% of male labor forc..."
349,"Unemployment, youth male (% of male labor forc...","Unemployment, youth male (% of male labor forc..."
350,"Unemployment, youth total (% of total labor fo...","Unemployment, youth total (% of total labor fo..."
351,"Unemployment, youth total (% of total labor fo...","Unemployment, youth total (% of total labor fo..."
352,Urban population,Urban population
353,Urban population (% of total),Urban population (% of total)
354,Urban population growth (annual %),Urban population growth (annual %)
355,Urban poverty headcount ratio at national pove...,Urban poverty headcount ratio at national pove...
356,"Wage and salaried workers, female (% of female...","Wage and salaried workers, female (% of female..."
357,"Wage and salaried workers, male (% of male emp...","Wage and salaried workers, male (% of male emp..."
358,"Wage and salaried workers, total (% of total e...","Wage and salaried workers, total (% of total e..."
359,"Water productivity, total (constant 2010 US$ G...","Water productivity, total (constant 2010 US$ G..."
360,Women making their own informed decisions rega...,Women making their own informed decisions rega...
361,Women who were first married by age 15 (% of w...,Women who were first married by age 15 (% of w...
362,Women who were first married by age 18 (% of w...,Women who were first married by age 18 (% of w...

NameError: name 'SH' is not defined